version: 2

before:
  hooks:
    - rm -rf dist
    - go mod tidy
    - go generate ./...

builds:
  - id: ndfc-collector
    binary: ndfc-collector
    main: ./cmd/ndfc-collector
    targets:
      - windows_amd64_v1
      - linux_amd64_v1
      - darwin_arm64
    env:
      - CGO_ENABLED=0
    tags:
      - netgo
      - static_build

release:
  github:
    owner: cisco-open
    name: ndfc-collector

archives:
  - id: collector
    formats: ["zip"]
    files:
      - README.md
      - LICENSE
      - ndfc_collector.py
